config/routes.rb
Rails.application.routes.draw do
  resources :users do
    
  end
  
  resources :sessions do
    
  end
  
  resources :tops do
    
  end
  
  resources :favorites, only: [:create, :destroy]
  
  resources :webpages do
  end
  
  get '/blogs', to: 'blogs#index'
  
  resources :blogs do
    collection do
      post :confirm
    end
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :blog_images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :title, presence: true
  #validates :content, presence: true
  validates :content,    length: { in: 1..140 } 
end

app/models/blog_image.rb
class BlogImage < ApplicationRecord
  belongs_to :blog
  
  mount_uploader :image, ImageUploader
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
   
  before_save { email.downcase! }
  has_secure_password
  
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }
  
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_images_controller.rb
class BlogImagesController < ApplicationController
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  include SessionsHelper
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :current_user, only: [:new, :show, :edit, :destroy]
  
  def index
    @blogs = Blog.all
  end

  def new
    if !logged_in?
      redirect_to new_session_path
    end
    if params[:back]
      @blog = Blog.new(blog_params)
      
      if !params[:cache].nil? && params[:cache][:image].present?
        # Feedテーブルの中に、imageのカラム（画像アップロード用のカラム）以外のものがある場合、
        # Feed.newではなくFeed.new(feed_params)にする。
        @blog_image = BlogImage.new(blog_image_params)
        # 画像保存（create）の際に、キャッシュから画像を復元してnewに入れる
        # newに戻る際も、createと同様に復元処理が必要となる。
        @blog_image.image.retrieve_from_cache! params[:cache][:image]
      end
      
    else
      @blog = Blog.new
      @blog_image = BlogImage.new()
    end
    @blog.user = current_user

  logger.debug("Debug blog new-----")
  logger.debug(@blog)
  logger.debug(@blog.user)

  end
  
  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user
    
    logger.debug("Debug blog create-----")
    logger.debug(@blog)
    logger.debug(@blog.user)
    
    #if !params[:cache].nil?
    if !params[:cache].nil? && params[:cache][:image].present?
      logger.debug("Debug blog_image create-----")
      # Feedテーブルの中に、imageのカラム（画像アップロード用のカラム）以外のものがある場合、
      # Feed.newではなくFeed.new(feed_params)にする。
      @blog_image = BlogImage.new(blog_image_params)
      # 画像保存（create）の際に、キャッシュから画像を復元してnewに入れる
      # newに戻る際も、createと同様に復元処理が必要となる。
      @blog_image.image.retrieve_from_cache! params[:cache][:image]
    end
    
    logger.debug("Debug blog_image create-----")
    logger.debug(@blog_image)
    
    if @blog.save
      if !params[:cache].nil? && params[:cache][:image].present?
        @blog_image.blog_id = @blog.id
        @blog_image.save
      end
      # 作成したことをメールで通知します
      BlogUserMailer.blog_user_mail(@blog).deliver
      
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      # 入力フォームを再描画します。
      render 'new'
    end
    
  end
  
  def show
    if !logged_in?
      redirect_to new_session_path
    end
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
    @blog_image = @blog.blog_images.find_by(blog_id: @blog.id)
  end
  
  def edit
    if !logged_in?
      redirect_to new_session_path
    end
    @blog_image = @blog.blog_images.find_by(blog_id: @blog.id)
  end
  
  def update
    if @blog.update(blog_params)
      # 編集したことをメールで通知します
      BlogUserMailer.blog_user_mail(@blog).deliver
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    if !logged_in?
      redirect_to new_session_path
    end
    @blog.destroy
    # 削除したことをメールで通知します
    BlogUserMailer.blog_user_mail(@blog).deliver
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end
  
  def confirm
    @blog = Blog.new(blog_params)
    @blog.user = current_user
    
    logger.debug("Debug blog confirm-----")
    logger.debug(@blog)
    logger.debug(@blog.user)
    
    #@blog_image = BlogImage.new(image: params[:blog][:image])
    @blog_image = BlogImage.new(blog_image_params)
    
    logger.debug("Debug blog_image confirm-----")
    logger.debug(@blog_image)

    render :new if @blog.invalid?
  end
  
  private
  def blog_params
    params.require(:blog).permit(:title, :content )
  end
  
  def blog_image_params
    params.require(:blog).permit(:image, :image_cache)
  end

  
  private
  def set_blog
    @blog = Blog.find(params[:id])
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  include SessionsHelper
  
  def create

    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    logger.debug("Debug favorite create-----")
    logger.debug(favorite)
    #redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
    redirect_to blogs_url
  end

  def destroy
    favorite = current_user.favorites.find_by(blog_id: params[:blog_id]).destroy
    #redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
    redirect_to blogs_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      # ログイン失敗した場合
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    logger.debug("Debug user create-----")
    logger.debug(@user.image)
    if @user.save
      # 保存の成功した場合の処理
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
    @favorite_blogs = @user.favorite_blogs
    logger.debug("Debug user show-----")
    logger.debug(@favorite_blogs)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :image)
  end
end

app/controllers/webpages_controller.rb
class WebpagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_images_helper.rb
module BlogImagesHelper
  
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/webpages_helper.rb
module WebpagesHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <!-- 確認画面から新規作成画面に戻った時に、 -->
    <!-- アップロードした画像を表示させるための記述 -->
    <%= image_tag(@blog_image.image.url) if @blog_image.present? && !@blog_image.id.nil? %>
    <%= form.file_field :image, id: :blog_image %>
    <!-- 確認画面から新規作成画面に戻った時に情報を保持するための記述 -->
    <%= form.hidden_field :image_cache %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to 'ブログ一覧画面にもどる', '/blogs', class: 'btn btn-primary'%>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= image_tag(@blog_image.image) %>
  <%= hidden_field_tag :"cache[image]",@blog_image.image.cache_name %>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= hidden_field_tag :"cache[image]",@blog_image.image.cache_name %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2>ブログを編集する</h2>

<%= render 'form' %>

app/views/blogs/index.html.erb
<div class="container">
  <div id="new-blog-link">
    <%= link_to '新規ブログを作成する', new_blog_path %>
  </div>

  <% @blogs.each do |blog| %>
    <div class="col-xs-12 col-md-6 blog-panel">
      <div class="blog-panel">
        <h2><%= blog.title %></h2>
        <p><%= blog.content %></p>
        <p><%= blog.user.name %></p>
        <div class="blog-links">
          <% if logged_in? %>
            <%= link_to 'Show', blog, class: 'btn btn-default' %>
            <% if blog.user_id == current_user.id %>
              <%= link_to 'Edit', edit_blog_path(blog), class: 'btn btn-info' %> |
              <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>

<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<p>作成者: <%= @blog.user.name %></p>
<% if !@blog_image.nil? %>
  <% if !@blog_image.image.nil? %>
    <p><%= image_tag(@blog_image.image.url) %></p>
  <% end %>
<% end %>

<%= link_to 'ブログ一覧画面にもどる', blogs_path, class: 'btn btn-primary' %>


<% if @blog.user_id == @current_user.id %>
  <%= link_to "ブログを編集する", edit_blog_path(@blog.id), class: 'btn btn-primary' %>
<% else %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(blog_id: @blog.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/tops/index.html.erb
<div class="container">
  <article>
    <div class="contents">
      <div class="row row-eq-height">
        <div class="col-sm-6 col-md-4">
          <%= image_tag 'oka1.jpg' ,class: "img-responsive" ,margin:0 %>
        </div>
        <div class="col-sm-6 col-md-4">
          <%= image_tag 'umi1.jpg' ,class: "img-responsive" %>
        </div>
        <div class="col-sm-6 col-md-4">
         <%= image_tag 'sora1.jpg' ,class: "img-responsive" %>
        </div>
      </div>
    </div>
    <div class="topic">
      <ul>
        <li>Bootstrapの課題のアプリケーションです！</li>
        <li>メニューで「ブログ」を選ぶとブログの追加とかができるようになります！</li>
      </ul>
    </div>
  </article>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form', user: @user %>

<%= form_with(model: @user, local: true) do |f| %>  
  <ul>
    <li>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </li>
    
    <li>
    <%= f.label :email %>
    <%= f.email_field :email %>
    </li>
    
    <li>
    <%= f.label :password %>
    <%= f.password_field :password %>
    </li>
    
    <li>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    </li>
  </ul>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, id: :user_image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<% @favorite_blogs.each do |blog| %>
  <div class="col-xs-12 col-md-6 blog-panel">
    <div class="blog-panel">
      <h2><%= blog.title %></h2>
        <p><%= blog.content %></p>
        <p><%= blog.user.name %></p>
    </div>
  </div>
<% end %>

<p>
  <strong>Image:</strong>
  <%= image_tag @user.image %>
</p>

app/views/webpages/index.html.erb
<div class="container">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
          <span class="sr-only">Bootstrap</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Bootstrap</a>
      </div>
      <div id="gnavi" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="">top</a></li>
          <li><a href="">menu1</a></li>
          <li><a href="">menu2</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <article>
    <div class="contents">
      <ul class="row">
        <li class="col-sm-6 col-md-3">contents1</li>
        <li class="col-sm-6 col-md-3">contents2</li>
        <li class="col-sm-6 col-md-3">contents3</li>
        <li class="col-sm-6 col-md-3">contents4</li>
      </ul>
    </div>
    <div class="topic">
      <ul>
        <li>bootstrapを使ってレスポンシブデザインを実現しよう！</li>
        <li>やればできる！bootstrapを使ってみよう！</li>
        <li>怖くない！レスポンシブデザインができるようになればWebアプリケーションもワンランク上に！</li>
      </ul>
    </div>
  </article>
</div>